### ISSUE TITLE
Error: 40028305 [Superheavy Samurai Soulclaw]

### ISSUE THREAD

**Issue by YGO5upp0r73r** [mycard/ygopro-images#7]
Thank you for updating the card pics.

I did however notice one mistake.

It should be Level 2, not Level 1.

**Comment by zh99998** [comment]
these pictures is not generated by me. I just upload.
I'll re-generate all pictures (with another template) after i bring mycard service up.

**Comment by mercury233** [comment]
I think this issue will be fixed in the next release by @woodee
